export const drivers = [
    {id: 1, name: "Max Verstappen", team: "Red Bull Racing"},
    {id: 2, name: "Sergio Perez", team: "Red Bull Racing"},
    {id: 3, name: "Lewis Hamilton", team: "Mercedes"},
    {id: 4, name: "George Russell", team: "Mercedes"},
    {id: 5, name: "Charles Leclerc", team: "Ferrari"},
    {id: 6, name: "Carlos Sainz", team: "Ferrari"},
    {id: 7, name: "Lando Norris", team: "McLaren"},
    {id: 8, name: "Oscar Piastri", team: "McLaren"},
    {id: 9, name: "Fernando Alonso", team: "Aston Martin"},
    {id: 10, name: "Lance Stroll", team: "Aston Martin"},
    {id: 11, name: "Esteban Ocon", team: "Alpine"},
    {id: 12, name: "Pierre Gasly", team: "Alpine"},
    {id: 13, name: "Alexander Albon", team: "Williams"},
    {id: 14, name: "Logan Sargeant", team: "Williams"},
    {id: 15, name: "Valtteri Bottas", team: "Alfa Romeo"},
    {id: 16, name: "Guanyu Zhou", team: "Alfa Romeo"},
    {id: 17, name: "Kevin Magnussen", team: "Haas"},
    {id: 18, name: "Nico Hülkenberg", team: "Haas"},
    {id: 19, name: "Yuki Tsunoda", team: "AlphaTauri"},
    {id: 20, name: "Daniel Ricciardo", team: "AlphaTauri"}
  ];